module.exports = {
    adjectives: ["adorable","adventurous","aggressive","agreeable","alert","alive","amused","angry","annoyed","annoying","anxious","arrogant","ashamed",
    "attractive","average","awful","bad","beautiful","better","bewildered","black","bloody","blue","blue-eyed","blushing","bored","brainy","brave","breakable",
    "bright","busy","calm","careful","cautious","charming","cheerful","clean","clear","clever","cloudy","clumsy","colorful","combative","comfortable","concerned",
    "condemned","confused","cooperative","courageous","crazy","crowded","cruel","curious","cute","dangerous","dark","defeated","defiant","delightful",
    "determined","different","difficult","disgusted","distinct","disturbed","dizzy","doubtful","drab","dull","eager","easy","elated","elegant","embarrassed",
    "enchanting","encouraging","energetic","enthusiastic","envious","evil","excited","expensive","exuberant","fair","faithful","famous","fancy","fantastic","fierce","filthy","fine","foolish",
    "fragile","frail","frantic","friendly","frightened","funny","gentle","gifted","glamorous","gleaming","glorious","good","gorgeous","graceful","grieving","grotesque","grumpy","handsome","happy",
    "healthy","helpful","helpless","hilarious","homeless","homely","horrible","hungry","hurt","ill","important","impossible","inexpensive","innocent","inquisitive","itchy","jealous","jittery",
    "jolly","joyous","kind","lazy","light","lively","lonely","long","lovely","lucky","magnificent","misty","modern","motionless","muddy","mushy","mysterious","nasty","naughty","nervous",
    "nice","nutty","obedient","obnoxious","odd","old-fashioned","open","outrageous","outstanding","panicky","perfect","plain","pleasant","poised","poor","powerful","precious","prickly","proud",
    "putrid","puzzled","quaint","real","relieved","repulsive","rich","scary","selfish","shiny","shy","silly","sleepy","smiling","smoggy","sore","sparkling","splendid","spotless","stormy",
    "strange","stupid","successful","super","talented","tame","tasty","tender","tense","terrible","thankful","thoughtful","thoughtless","tired","tough","troubled","uninterested",
    "unsightly","unusual","upset","uptight","vast","victorious","vivacious","wandering","weary","wicked","wild","witty","worried","worrisome", "wrong","zany","zealous"],
    nouns: ["Actor","Gold","Painting","Advertisement","Grass","Parrot","Afternoon","Pencil","Airport","Guitar","Piano","Ambulance","Hair","Pillow","Animal",
    "Hamburger","Pizza","Answer","Helicopter","Planet","Apple","Helmet","Plastic","Holiday","Honey","Potato","Balloon","Horse","Queen","Banana","Hospital",
    "Quill","Battery","House","Rain","Beach","Hydrogen","Rainbow","Beard","Ice","Raincoat","Bed","Insect","Refrigerator","Belgium","Insurance","Restaurant","Iron","River","Branch",
    "Island","Rocket","Breakfast","Jackal","Room","Brother","Jelly","Rose","Camera","Jewellery","Candle","Sandwich","Car","Juice","Kangaroo","Scooter","Carpet","King","Shampoo",
    "Cartoon","Kitchen","Shoe","Kite","Soccer","Church","Knife","Spoon","Crayon","Lamp","Stone","Crowd","Lawyer","Sugar","Leather","Library","Diamond","Lion","Television","Dinner",
    "Lizard","Tent","Disease","Lock","Doctor","Tomato","Dog","Lunch","Toothbrush","Dream","Machine","Traffic","Dress","Magazine","Train","Easter","Magician","Truck","Egg",
    "Eggplant","Market","Umbrella","Match","Van","Elephant","Microphone","Vase","Energy","Monkey","Vegetable","Engine","Morning","Vulture","Motorcycle","Wall","Evening",
    "Nail","Whale","Eye","Napkin","Window","Family","Needle","Wire","Nest","Xylophone","Fish","Yacht","Flag","Night","Yak","Flower","Notebook","Zebra",
    "Football","Ocean","Zoo","Forest","Oil","Garden","Fountain","Orange","Gas","Oxygen","Furniture","Oyster","Glass","Garage","Ghost"]
}